# Generated by Django 3.1.7 on 2021-05-04 15:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=6)),
                ('mobile', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(default='comp@comp.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=30)),
                ('email', models.EmailField(default='comp@comp.com', max_length=254)),
                ('mobile', phone_field.models.PhoneField(default=1234567890, help_text='Contact phone number', max_length=31)),
                ('dob', models.DateField(default=django.utils.timezone.now, max_length=8)),
                ('appointment_date', models.DateField(default=datetime.date.today, max_length=8)),
                ('appointment_time', models.CharField(choices=[('10 am', '10 am'), ('11 am', '11 am'), ('12 pm', '12 pm')], default='10 am', max_length=10)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('waiting_status', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Registered')),
                ('specialization', models.CharField(max_length=70)),
                ('email', models.EmailField(default='comp@comp.com', max_length=254)),
                ('mobile', phone_field.models.PhoneField(default=1234567890, help_text='Contact phone number', max_length=31)),
                ('dob', models.DateField(default=datetime.date.today, max_length=8)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
            ],
        ),
    ]
