# Generated by Django 3.1.7 on 2021-04-22 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='registration_date',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='patient',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='waiting_status',
            field=models.BooleanField(default=True),
        ),
    ]
