# Generated by Django 3.1.7 on 2021-05-06 09:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='appointment_time',
            field=models.CharField(choices=[('10 am', '10 am'), ('11 am', '11 am'), ('12 pm', '12 pm'), ('1 pm', '1 pm'), ('2 pm', '2 pm'), ('3 pm', '3 pm'), ('4 pm', '4 pm')], default='10 am', max_length=10),
        ),
        migrations.CreateModel(
            name='Patient_Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('email', models.EmailField(default='comp@comp.com', max_length=254)),
                ('mobile', phone_field.models.PhoneField(default=1234567890, help_text='Contact phone number', max_length=31)),
                ('feedback', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
            ],
        ),
    ]
