# Generated by Django 3.1.7 on 2021-05-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210501_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='email',
            field=models.EmailField(default='comp@comp.com', max_length=254),
        ),
    ]
