# Generated by Django 3.1.7 on 2021-05-03 04:34

from django.db import migrations, models
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_hospital_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, max_length=8),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default='comp@comp.com', max_length=254),
        ),
        migrations.AddField(
            model_name='doctor',
            name='mobile',
            field=phone_field.models.PhoneField(default=1234567890, help_text='Contact phone number', max_length=31),
        ),
    ]
