# Generated by Django 3.1.7 on 2021-05-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210503_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='doctor',
            new_name='hospital',
        ),
    ]
